site:
  title: 'Knowledge'
  url: 'https://pk.stag.lol'
  start_page: 'ROOT::index.adoc'
content:
  edit_url: null
  branches: [ 'HEAD' ]
  worktrees: true # use uncommitted changes if any
  sources:
    - url: './../'
      start_paths: 'components/*'
ui:
  bundle:
    url: './../build/bundle'
  supplemental_files: './../build/ui'
output:
  clean: true
  dir: './../build/site'
asciidoc:
  attributes:
    # links become 'google.com' instead of 'https://google.com'
    hide-uri-scheme: true
    # heading ids (eg. for 'My Heading') are #my-heading instead of #_my_heading
    idprefix: ''
    idseparator: '-'
    # enable extra features
    experimental: true
    # html lang attribute
    lang: 'en-US'
    # anchor links on mouse hover over headings
    sectanchors: true
    # max depth of ToC
    toclevels: 3
    # number MathJax equations
    eqnums: 'all'
    # latex support
    stem: 'latexmath'
    # enable icons
    icons: 'font'
    # when one tab is selected, change other tab groups to the tab with the same name
    tabs-sync-option: true
  extensions:
    - '@asciidoctor/tabs'
antora:
  extensions:
    - '@antora/lunr-extension'
    - require: './../build/js/antora-atom/antora-atom.js'
      feed_options:
        author:
          name: 'stag-enterprises'
          email: 'x@stag.lol'
        copyright: '2025-present CC BY-SA 4.0'
        icon: 'https://stag.lol/favicon.ico'
