site:
  title: 'Knowledge'
  url: 'https://pk.stag.lol'
  start_page: 'ROOT::index.adoc'
content:
  edit_url: null
  branches: [ 'HEAD' ]
  worktrees: true # use uncommitted changes if any
  sources:
    - url: './../'
      start_paths: 'components/*'
ui:
  bundle:
    url: './../build/bundle'
  supplemental_files: './ui'
output:
  clean: true
  dir: './../build/site'
asciidoc:
  attributes:
    hide-uri-scheme: true
antora:
  extensions:
    - '@antora/lunr-extension'
    - require: './../build/js/antora-atom/antora-atom.js'
      feed_options:
        author:
          name: 'stag-enterprises'
          email: 'x@stag.lol'
        copyright: '2025-present CC BY-SA 4.0'
        icon: 'https://stag.lol/favicon.ico'
